[workspace]
members = ["crates/crypto", "crates/evm"]
resolver = "3"

[workspace.package]
version = "0.1.0-rc.1"
edition = "2024"
license = "Apache-2.0"
homepage = "https://boundless.network/"
repository = "https://github.com/boundless-xyz/risc0-crypto"

[workspace.lints.rust]
rust-2018-idioms = "deny"
unreachable-pub = "warn"
unused-must-use = "deny"

[workspace.lints.rustdoc]
all = "warn"

[workspace.lints.clippy]
use-self = "warn"
missing-const-for-fn = "warn"
redundant-clone = "warn"
dbg-macro = "warn"
uninlined-format-args = "warn"
manual-string-new = "warn"
